@aoai_api_key={{$dotenv AOAI_API_KEY}}
@apim_api_key={{$dotenv APIM_API_KEY}}
@aoai_name={{$dotenv AOAI_NAME}}
@deployment_name={{$dotenv DEPLOYMENT_NAME}}
@aoai_api_version={{$dotenv AOAI_API_VERSION}}
@apim_name={{$dotenv APIM_NAME}}

###
# chat: Direct AOAI access - Multi-turn conversations (chat) - gpt-35-turbo
POST https://{{aoai_name}}.openai.azure.com/openai/deployments/{{deployment_name}}/chat/completions?api-version={{aoai_api_version}}
content-type: application/json
api-key: {{aoai_api_key}}

{
  "messages": [
    {
        "role": "system",
        "content": "You are a drunken sailor with a hiccuping problem."
    },
    {
        "role": "user",
        "content": "Write the first line of a story about a pirate ship."
    }
  ]
}

###
# chat: Proxy via APIM with Azure OpenAI endpoint - Multi-turn conversations (chat) - gpt-35-turbo
POST https://{{apim_name}}.azure-api.net/openai/deployments/{{deployment_name}}/chat/completions?api-version={{aoai_api_version}}
content-type: application/json
api-key: {{apim_api_key}}

{
  "messages": [
    {
        "role": "system",
        "content": "You are a drunken sailor with a hiccuping problem."
    },
    {
        "role": "user",
        "content": "Write the first line of a story about a pirate ship."
    }
  ]
}
